-- ========================================================
-- SCRIPT DE BANCO DE DADOS SUPABASE (POSTGRESQL)
-- Cole este script no SQL Editor do seu projeto no Supabase
-- ========================================================

-- 1. Tabela de Contas Fixas
CREATE TABLE IF NOT EXISTS public.contas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dia_vencimento INT NOT NULL CHECK (dia_vencimento BETWEEN 1 AND 31),
    descricao TEXT NOT NULL,
    ativa BOOLEAN DEFAULT TRUE,
    criada_em TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Tabela de Pagamentos Mensais
CREATE TABLE IF NOT EXISTS public.pagamentos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conta_id BIGINT REFERENCES public.contas(id) ON DELETE CASCADE,
    mes_ano VARCHAR(7) NOT NULL, -- Formato: YYYY-MM
    pago_por TEXT,
    pago_em TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(conta_id, mes_ano)
);

-- Habilitar Row Level Security (RLS) e políticas públicas de leitura/escrita
ALTER TABLE public.contas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pagamentos ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Permitir leitura publica de contas" ON public.contas FOR SELECT USING (true);
CREATE POLICY "Permitir insercao publica de contas" ON public.contas FOR INSERT WITH CHECK (true);
CREATE POLICY "Permitir atualizacao publica de contas" ON public.contas FOR UPDATE USING (true);
CREATE POLICY "Permitir exclusao publica de contas" ON public.contas FOR DELETE USING (true);

CREATE POLICY "Permitir leitura publica de pagamentos" ON public.pagamentos FOR SELECT USING (true);
CREATE POLICY "Permitir insercao publica de pagamentos" ON public.pagamentos FOR INSERT WITH CHECK (true);
CREATE POLICY "Permitir atualizacao publica de pagamentos" ON public.pagamentos FOR UPDATE USING (true);
CREATE POLICY "Permitir exclusao publica de pagamentos" ON public.pagamentos FOR DELETE USING (true);

-- 3. Carga Inicial de Dados (27 Contas Fixas Extraídas do Word)
INSERT INTO public.contas (dia_vencimento, descricao) VALUES
(1, 'Aluguel Base SC'),
(3, 'Aluguel Base NH'),
(3, 'Água Base SC'),
(8, 'RGE Terreno SL'),
(10, 'Aluguel PR – AGUA VERDE'),
(10, 'Aluguel AP SC'),
(10, 'Condomínio SC'),
(10, 'Consórcio HS'),
(10, 'Rastreadores'),
(10, 'Seguros Star'),
(10, 'Claro NH'),
(10, 'Sebratel SL'),
(10, 'Luz APE – CELESC – SC'),
(10, 'Luz – BASE CELESC SC'),
(10, 'ALUGUEL – DESTAK – SC'),
(10, 'ALUGUEL – CONQUISTA – SL'),
(15, 'Ticket Combustível'),
(15, 'CLARO SC'),
(15, 'RECH TEC'),
(15, 'RECH JLE'),
(15, 'SMARTEC'),
(17, 'Contas Vivo e Claro'),
(18, 'Parcela Fluence'),
(18, 'RGE Base SL'),
(20, 'CLARO PR'),
(24, 'AGUA – COMUSA NH'),
(30, 'TICKET COMBUSTIVEL');
